app = "lingoscribe"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [http_service.tls]
    minimum_version = "1.2"
    maximum_version = "1.3"

[env]
  PORT = "8080"

[mounts]
  source = "lingoscribe_data"
  destination = "/app/storage"